### ISSUE TITLE
Custom zip implementation?

### ISSUE THREAD

**Issue by jpreese** [bitgenics/deterministic-zip#3]
I was looking over this project and from what I can tell you're essentially doing your own zip implementation. 

Why was this decision made over just using something like jszip and then modifying the timestamp of that file? Have you tried this approach or are aware of any difficulties with this approach?

**Comment by evanderkoogh** [comment]
Yes and no. For the actual zipping of the files I use the NodeJS implementation of zip. And that is the really difficult bit I certainly wouldn’t want to do myself. 
What this does is however is an implementation of the zip-file format, which is still not trivial, because it’s all sort-of-but-not-quite fix length encoding, but not nearly as impossible as zip itself.

The problem with zip files is that it is extremely loosely specified, especially beyond the basics. If I remember correctly, there are about 2 or 3 different ways to encode files, with time stamps. So if I went the route of changing another library I would be forced to dive into every single detail they could do to output. And then be tied to them.
And in the end it wouldn’t even be easier, because I would still have to do all the parsing of the file.

It was much easier to write out a zip file format myself. I could also only worry about the required aspects, guarantee that it would be deterministic etc. What if jszip suddenly decides to encode permissions? Which way do they pick? Do they do something differently on Windows?

Closing this now, but feel free to follow up with any other questions/clarifications.

**Comment by jpreese** [comment]
I could see the argument for environments. You don't necessarily know which each zip implementation will do to its contents.

What sparked the question was a friend was looking for this exact solution. A way to zip files in a deterministic way. I suggested you just modify all of the contents of the zip to have the same date, and then zip up the file. In our testing, it resulted in the same hash.

```powershell
[datetime]$date = (Get-Date -Date 01/01/1980)

(Get-ChildItem -Path $extractPath -Recurse -File) | ForEach-Object {$_.CreationTime = $date
$_.LastAccessTime = $date
$_.LastWriteTime = $date }

Compress-Archive -Path "$extractPath/*" -DestinationPath $destinationZip
```

This was done in `powershell`, but it takes all of the files to be zipped, modifies their access/write times to 1/1/1980 and then zips them.

**Comment by evanderkoogh** [comment]
That could certainly work. Certainly if you know you are always going to be running on Windows.

I needed something that could work on multiple environments. Now I assume your zip implementation doesn’t use any file metadata? Like file permissions?
